# Configuraciones para H2

spring.datasource.url=jdbc:h2:mem:vetdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=vetuser
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# Logging de pruebas más limpio
logging.level.org.springframework.test=INFO
